export const queryKeys = {
  cart: ["cart"] as const,
  comments: (productId: string) => ["comments", productId] as const,
  products: (filters: object) => ["products", filters] as const,
  articles: (filters: object) => ["articles", filters] as const,
  favorites: ["favorites"] as const,
  favoriteCount: ["favorites", "count"] as const,
  favoriteIds: ["favorites", "ids"] as const,
  myOrders: (filters: object = {}) => ["my-orders", filters] as const,
  myComments: (filters: object = {}) => ["my-comments", filters] as const,
  myTickets: (filters: object = {}) => ["my-tickets", filters] as const,
  departments: ["departments"] as const,
  notifications: ["notifications"] as const,
  admin: {
    all: ["admin"] as const,
    stats: (days: number) => ["admin", "stats", days] as const,
    orders: (filters: object = {}) => ["admin", "orders", filters] as const,
    products: (filters: object = {}) => ["admin", "products", filters] as const,
    users: (filters: object = {}) => ["admin", "users", filters] as const,
    comments: (filters: object = {}) => ["admin", "comments", filters] as const,
    articles: (filters: object = {}) => ["admin", "articles", filters] as const,
    tickets: (filters: object = {}) => ["admin", "tickets", filters] as const,
    coupons: (filters: object = {}) => ["admin", "coupons", filters] as const,
    contacts: (filters: object = {}) => ["admin", "contacts", filters] as const,
    newsletter: (filters: object = {}) => ["admin", "newsletter", filters] as const,
    carts: (filters: object = {}) => ["admin", "carts", filters] as const,
    cart: (id: string) => ["admin", "cart", id] as const,
    categoryFilters: (slug: string) => ["admin", "category-filters", slug] as const,
  },
};
